### PR TITLE
v1: backport sort commands by name

### PR DESCRIPTION
**Pull request by MaximilianMeister**
this is backporting the commit from https://github.com/urfave/cli/issues/575

command: enable ordering commands by name

(cherry picked from commit ac772237b96509d5150567da31ba6c6c3897d452)

### CODE REVIEW

**Comment by jszwedko** [comment]
This was actually missing because I hadn't recently merged master into the `v1` branch, but have done so now. Thank you for pointing this out @MaximilianMeister !

**Comment by MaximilianMeister** [comment]
@jszwedko thanks ! do you plan to make a new release tag as well? and make the gopkg.in link point to there as well?

**Comment by jszwedko** [comment]
@MaximilianMeister definitely; I'm doing a sweep now, but will try to get a release out this week.

**Comment by MaximilianMeister** [comment]
> definitely; I'm doing a sweep now, but will try to get a release out this week.

great, thanks again!

**Comment by MaximilianMeister** [comment]
@jszwedko btw do you plan to include this in a next stable release? would be great to have that commits when running `govendor fetch gopkg.in/urfave/cli.v1`

**Pull request closed without merging**
