### PR TITLE
Replace space only lines in help with only newline

### PR DESCRIPTION
**Pull request by cehoffman**
## What type of PR is this?

- bug

## What this PR does / why we need it:

The changes to automatically indent description text added potential for empty lines that have only the padding text. As a consumer of this library, I have example tests to validate the help text appears as I intend. This was useful in helping to detect the change of description indent between 2.2 and 2.3. However I can no longer use these tests because it would require comment lines with trailing whitespace which is removed with tools like `go fmt` and `goimports`.

## Which issue(s) this PR fixes:

_(REQUIRED)_

## Special notes for your reviewer:

_(fill-in or delete this section)_

## Testing

Made an example test with expected output.

## Release Notes

_(REQUIRED)_

```release-note
NONE
```

### CODE REVIEW

**Review by lynncyrin — CHANGES_REQUESTED** [review]
Can you add a test case for this?

**Comment by meatballhat** [comment]
@cehoffman Hello and sorry for the delay and auto-close via stalebot. Are you up for [adding a test for this change](https://github.com/urfave/cli/pull/1221#pullrequestreview-575061528)?

**Comment by abitrolly** [comment]
I fixed the issue with trailing whitespace in https://github.com/urfave/cli/pull/1513

@cehoffman can you check that the fix works for you?

**Comment by dearchap** [comment]
Closing

**Pull request closed without merging**
