### PR TITLE
Add readonly flags to CI

### PR DESCRIPTION
**Pull request by lynncyrin**
followup from https://github.com/urfave/cli/pull/892#discussion_r325964810

### CODE REVIEW

**Comment by lynncyrin** [comment]
🤷‍♀ no idea whyt CI is failing

**Comment by AudriusButkevicius** [comment]
Seems like head has some broken tests? Strange.

**Comment by saschagrunert** [comment]
Might be related to `gfmrun` and not this repository.

**Comment by asahasrabuddhe** [comment]
Let me take a look at this

**Comment by lynncyrin** [comment]
I'm gonna close this b/c I don't feel like working on it, anyone else is free to create a new PR for this change though!

**Pull request closed without merging**
