### PR TITLE
WIP: Fix error where app name would be used instead of command help name

### PR DESCRIPTION
**Pull request by Strift**
This should fix the issue #557 

Sorry this is WIP. I will update when I'm done.

### CODE REVIEW

**Comment by Strift** [comment]
I'm afraid I do not understand what is the actual problem.

Failed assertions happens at:
- app_test.go:1097
- app_test.go:1100
- app_test.go:1159
- app_test.go:1162
- app_test.go:1190
- app_test.go:1193

But all the outputs look good to me... :/

**Comment by Strift** [comment]
I know there are failed assertions when running this fork. But I have no idea why are the tests failing.

@jszwedko If you could tell me what I should do to make the tests pass / refactor the tests, I would gladly investigate a bit more.

**Comment by jszwedko** [comment]
Hi @Strift,

Thanks for taking a crack at this! Apologies for the delay, just getting back from traveling.

I believe this change does break behavior that was introduced in https://github.com/urfave/cli/pull/267 (see that thread for more discussion) which is why you see the failing tests here.

I think there are more nuances described in #557 than what you are describing here though. I think to address that issue a more drastic overhaul of the help system will be required to handle all of the cases described there. I think it can be simplified along the way though.

**Comment by lynncyrin** [comment]
Given that this PR is from years ago, I think I'm comfortable closing it 🙂 feel free to re-open / open a new PR if there's still interest here!

**Pull request closed without merging**
