### PR TITLE
GitHub actions windows

### PR DESCRIPTION
**Pull request by lynncyrin**
## Motivation

Fixes https://github.com/urfave/cli/issues/995

## Context

Continued from https://github.com/urfave/cli/pull/970

### CODE REVIEW

**Comment by asahasrabuddhe** [comment]
@lynncyrin The windows builds are also fixed. Only the `appveyor` builds are failing as the file is removed.

**Comment by asahasrabuddhe** [comment]
@lynncyrin Could you help me understand the test-docs workflow?

**Comment by lynncyrin** [comment]
> Could you help me understand the test-docs workflow?

The idea behind separating the docs tests was primarily they are conceptually distinct from the other tests. That said, I added them to this PR when it was in a draft state, so I'm not (a) ready to or (b) interested in justifying them. I would dramatically rather they be removed, because I'm not interested in blocking this PR with some WIP changes of mine.

**Comment by asahasrabuddhe** [comment]
> > Could you help me understand the test-docs workflow?
> 
> The idea behind separating the docs tests was primarily they are conceptually distinct from the other tests. That said, I added them to this PR when it was in a draft state, so I'm not (a) ready to or (b) interested in justifying them. I would dramatically rather they be removed, because I'm not interested in blocking this PR with some WIP changes of mine.

I think this makes sense to me. I am all in to have separate workflows to test code and documentation. This would help us understand and locate the exact point of failure in case of failing tests. I would not like to have them removed just yet. I would instead prefer if we remove the documentation testing (gfmrun) and table of content generation from the other workflow steps and have them done separately.

**Comment by asahasrabuddhe** [comment]
@lynncyrin I don't think there remains much to be done here. The documentation flow is already separate and I think this is ready to be merged.

**Comment by lynncyrin** [comment]
@asahasrabuddhe you can review the PR, I can't though 😆 since I made it

**Comment by asahasrabuddhe** [comment]
@saschagrunert @rliebz could use some help here :)

**Comment by asahasrabuddhe** [comment]
@lynncyrin Please remove the appveyor checks so this can be merged

**Pull request merged**
