### PR TITLE
Update GitHub action

### PR DESCRIPTION
**Pull request by rliebz**
## What type of PR is this?

_(REQUIRED)_

- [ ] bug
- [x] cleanup  
- [ ] documentation
- [ ] feature

## What this PR does / why we need it:

_(REQUIRED)_

Bump go version to 1.16 and drop the codecov token, which is now
documented as not required for public repositories.

## Which issue(s) this PR fixes:

_(REQUIRED)_

Fixes https://github.com/urfave/cli/issues/1269

## Special notes for your reviewer:

_(fill-in or delete this section)_

Figured I'd bump the go version while I was in there, but `gfmrun` failed, and I figured it was better to get this change in now and work that out later, so that's still at 1.15. 

## Testing

_(fill-in or delete this section)_

If the pipeline passes, we're golden.

## Release Notes

_(REQUIRED)_

```release-note
NONE
```

### CODE REVIEW

**Comment by rliebz** [comment]
@lynncyrin Once we get this merged in, we should revoke the token from whatever account owns it. Looking at https://github.com/urfave/cli/pull/986 I'm guessing that's something you have access to.

**Comment by lynncyrin** [comment]
I do have access to it! 👍

**Review by lynncyrin — APPROVED** [review]
🙏🏽

**Comment by lynncyrin** [comment]
Token revoked ✅

**Pull request merged**
