### PR TITLE
Revert "Add `TakesFile` indicator to flag"

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Reverts urfave/cli#851

Suggest we rethink this before this spreads too far.

### CODE REVIEW

**Comment by lynncyrin** [comment]
@AudriusButkevicius can you give a more thorough explanation of why you're opening this PR? I don't have enough context to make a decision here.

**Comment by lynncyrin** [comment]
If we want to revert this, I think the reversion needs to come with a thorough explanation in the PR description. I don't understand why would should be reverting this, which means I am very likely to unknowingly approve similar changes like this in the future. If there's some API stability north star we are working towards, then it would help me out if that north star was described. My current state is that I have no idea why someone would / would not add a certain feature, and I need to be educated on this if the goal is for me to make decisions and moving the API to a good place.

**Comment by asahasrabuddhe** [comment]
Let's first finalize the discussion on #851 and then come to a conclusion about whether or not this PR is even necessary

**Comment by AudriusButkevicius** [comment]
The rationale is on the original PR

**Comment by lynncyrin** [comment]
I consider this PR blocked pending more discussion, similarly to https://github.com/urfave/cli/pull/860

**Comment by AudriusButkevicius** [comment]
We can probably close this and merge #860 before we release anything.

**Comment by lynncyrin** [comment]
> We can probably close this and merge #860 before we release anything.

👍

**Pull request closed without merging**
