### PR TITLE
repair md2man not found problem

### PR DESCRIPTION
**Pull request by pi-pi-miao**
## What type of PR is this?

_(REQUIRED)_

- [x] bug
- [ ] cleanup  
- [ ] documentation
- [ ] feature

## What this PR does / why we need it:

_(REQUIRED)_

## Testing

_(fill-in or delete this section)_

### CODE REVIEW

**Comment by pi-pi-miao** [comment]
> ## 这是什么类型的公关？
> _（需要）_
> 
> * [x]  虫子
> * [ ]  清理
> * [ ]  文件资料
> * [ ]  特征
> 
> ## 该PR的作用/我们为什么需要它：
    first run this pachage ,it report an error
> cannot find package "github.com/cpuguy83/go-md2man/v2/md2man
   then find that path is wrong and suggest add vendor 
> 
> ## 测试中
> _（填写或删除此部分）_


> ## What type of PR is this?
> _(REQUIRED)_
> 
> * [x]  bug
> * [ ]  cleanup
> * [ ]  documentation
> * [ ]  feature
> 
> ## What this PR does / why we need it:
> _(REQUIRED)_
> 
> ## Testing
> _(fill-in or delete this section)_

**Comment by pi-pi-miao** [comment]
> ## What type of PR is this?
> _(REQUIRED)_
> 
> * [x]  bug
> * [ ]  cleanup
> * [ ]  documentation
> * [ ]  feature
> 
> ## What this PR does / why we need it:
> when i run first it report an error
package github.com/cpuguy83/go-md2man/v2/md2man: cannot find package "github.com/cpuguy83/go-md2man/v2/md2man" in any of:

then i go get ,but not found 
so  i found that path is wrong ,maybe reference package update

so suggest add vendor 
> 
> ## Testing
> _(fill-in or delete this section)_

**Comment by pi-pi-miao** [comment]
> ## What type of PR is this?
> _(REQUIRED)_
> 
> * [x]  bug
> * [ ]  cleanup
> * [ ]  documentation
> * [ ]  feature
> 
> ## What this PR does / why we need it:
> when i run first it report an error
> package github.com/cpuguy83/go-md2man/v2/md2man: cannot find package "github.com/cpuguy83/go-md2man/v2/md2man" in any of:
> 
> then i go get ,but not found
> so i found that path is wrong ,maybe reference package update
> 
> so suggest add vendor
>

**Comment by lynncyrin** [comment]
hey @pi-pi-miao, someone has tried to make this same PR before => https://github.com/urfave/cli/pull/918

**Comment by pi-pi-miao** [comment]
> hey @pi-pi-miao, someone has tried to make this same PR before => #918

yeah ,but i Fixed the problem ,because i add vendor    ha,ha,ha

**Pull request closed without merging**
