### PR TITLE
Harmonize BeforeError handling

### LINKED ISSUE #1081: v2 feature: Make error message optional in BeforeFunc
## Checklist

* [X] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [X] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [X] Did you perform a search about this feature? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

Displaying the help message in case of error in BeforeFunc should be optional. In my case I am using the BeforeFunc to validate command context and fails if something goes wrong, and I don't want any help message displayed.

## Solution description

I have add a **HideHelpOnBeforeError** flag to allow to hide help message in case error happens in the BeforeFunc.

### PR DESCRIPTION
**Pull request by creekorful**
## What type of PR is this?

- [X] bug
- [ ] cleanup  
- [ ] documentation
- [ ] feature

## What this PR does / why we need it:

The error handling using **BeforeFunc** is now harmonized between **App#RunContext**, **App#RunAsSubcommand** & **Command#Run**.

## Which issue(s) this PR fixes:

Fixes #1081

## Release Notes

_(REQUIRED)_

```release-note
Error handling using BeforeFunc is now harmonized between App#RunContext, App#RunAsSubcommand and Command#Run.
```

### CODE REVIEW

**Comment by rliebz** [comment]
Thanks for following up! This is great.

I did a quick audit of the code base, it looks like there's one more `BeforeFunc` that prints command help in case of errors: https://github.com/urfave/cli/blob/4bb97e00e035272d48248f1d000534e73b76a1a8/command.go#L150-L157

Would you mind dropping the call to `ShowCommandHelp` there as well for consistency?

**Comment by creekorful** [comment]
> Thanks for following up! This is great.
> 
> I did a quick audit of the code base, it looks like there's one more `BeforeFunc` that prints command help in case of errors:
> 
> https://github.com/urfave/cli/blob/4bb97e00e035272d48248f1d000534e73b76a1a8/command.go#L150-L157
> 
> Would you mind dropping the call to `ShowCommandHelp` there as well for consistency?

Yup, my bad should have seen this one.

Done !

**Comment by creekorful** [comment]
Btw is it wanted that this logic is uncoupled and not centralised?

IMHO since the BeforeError handling is common (and this is wanted) between the 3 occurrences, I would have centralise the logic somewhere

**Comment by rliebz** [comment]
There's a lot of logic like this that I'd like to see centralized. There are subtle reasons why it's not that way right now, such as repeated logic for different types or handling named return parameters. Not that it can't be improved—it absolutely can be. But it's not necessarily easy.

**Pull request merged**
