### PR TITLE
Add `urfave_cli_no_docs` build tag

### PR DESCRIPTION
**Pull request by kolyshkin**
## What type of PR is this?

- feature

## What this PR does / why we need it:

Add urfave_cli_no_docs build tag
  
This removes the resulting binary dependency on cpuguy83/md2man and
russross/blackfriday, which saves more than 400 KB (more than 300 KB
once stripped) from the resulting binary.

## Which issue(s) this PR fixes:

none (although see some discussions in e.g. https://github.com/urfave/cli/issues/1055)

## Special notes for your reviewer:

none

## Testing

See last commit.

## Release Notes

```release-note
Added support for `urfave_cli_no_docs` tag to reduce the binary size by 300+ KB
in case your application is not using `ToMarkdown` and `ToMan` methods.
```

### CODE REVIEW

**Comment by kolyshkin** [comment]
Result of check-binary-size CI job, defaults:

> 1.7MB is the current binary size

Same with `urfave_cli_no_docs`: 

> 1.4MB is the current binary size

Are we planning on v3 yet? In there, we can move docs to a separate package, so it won't be compiled in unless explicitly included.

**Comment by meatballhat** [comment]
> Result of check-binary-size CI job, defaults:
> 
> > 1.7MB is the current binary size
> 
> Same with `urfave_cli_no_docs`:
> 
> > 1.4MB is the current binary size

🎉 🤘🏼 
 
> Are we planning on v3 yet? In there, we can move docs to a separate package, so it won't be compiled in unless explicitly included.

Added to [the list](https://github.com/urfave/cli/issues/833)!

**Review by meatballhat — APPROVED** [review]
🎉

**Comment by kolyshkin** [comment]
v1 backport: #1383

**Pull request merged**
