### PR TITLE
Release 1.22.1

### PR DESCRIPTION
**Pull request by asahasrabuddhe**
Summary

I wanted these PRs to be a part of 1.22.0 but owing to certain dependency issues it was not possible.  With 1.22.0 in place, I would like to propose this minor release that would include the new build system and support for `Go 1.13` in our latest stable version.

Let me know if we can include anything else.

Included PRs

#883 
#885

### CODE REVIEW

**Comment by lynncyrin** [comment]
I'm 👍 here! I'll give the actual approving review once the relevant PRs are merged.

**Comment by AudriusButkevicius** [comment]
We should address the deps issue before making a new release.

**Comment by asahasrabuddhe** [comment]
This is not a new release. This is merely a minor patch that was originally meant to be a part of 1.22.0 but could not be integrated then due to test failures caused by dependency issues.

What deps issue are you referring to? Could you reference it here?

**Comment by AudriusButkevicius** [comment]
Sorry, on the phone, about to catch a flight. #888 is what I am referring to.

**Comment by asahasrabuddhe** [comment]
Thanks! On it. Have a happy and safe journey

**Comment by asahasrabuddhe** [comment]
@Audrius The fix for the dep is already included in #885 

The issue is due to mismatched version of md2man library leading to an issue in mismatched version of black friday.

If you would just approve this, I'd make the release and the issue would get fixed :)

**Comment by AudriusButkevicius** [comment]
But this needs more than just approvals, it needs an actual release.

**Comment by asahasrabuddhe** [comment]
Yes but with your approval, it's one less required. We could also include #889 in this release. It's a nice quick fix!

**Comment by AudriusButkevicius** [comment]
Sure

**Comment by AudriusButkevicius** [comment]
We should document the procedure for releases as I am not sure if you've done everything required so would be more comfortable if @lynncyrin approves this too.

**Comment by asahasrabuddhe** [comment]
@urfave/cli would really appreciate if you could check this out quickly so that we can get done with this...

**Comment by Narendra-Kamath** [comment]
> 🚢

@lynncyrin will this release be done today?

**Comment by lynncyrin** [comment]
> will this release be done today?

Probably!

**Pull request merged**
