### PR TITLE
generate-flag-type: Use standard tag for generated code

### PR DESCRIPTION
**Pull request by dolmen**
... to prevent manual edit.

See official spec at https://golang.org/s/generatedcode.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
This needs a rebase. Also go generate could be wired in for the build process.

**Comment by asahasrabuddhe** [comment]
I also would like to remove the python dependency here and have the complete generation process in go. What do you guys think?

**Comment by AudriusButkevicius** [comment]
Sounds good.

**Comment by asahasrabuddhe** [comment]
Exactly. I will start working on this now. :)

**Comment by lynncyrin** [comment]
> I also would like to remove the python dependency here and have the complete generation process in go. What do you guys think?

Yes!!!!!!!!!!!!!!!!!!!!!!

**Comment by asahasrabuddhe** [comment]
#836 implements this and enhances it. Closing.

**Pull request closed without merging**
