### PR TITLE
Fix improper whitespace formatting in usageTemplate variable

### PR DESCRIPTION
**Pull request by caeret**
just fix usageTemplate variable in `template.go`

### CODE REVIEW

**Comment by bartekpacia** [comment]
Hi, thanks for the contribution!

Could you show a comparison of before/after?

**Review by bartekpacia — APPROVED** [review]

**Comment by caeret** [comment]
```go
// test.go
package main

import (
	"os"

	cli "github.com/urfave/cli/v2"
)

func main() {
	app := cli.NewApp()
	app.ArgsUsage = "[arg1]"
	app.Commands = []*cli.Command{
		{
			Name:      "cmd1",
			ArgsUsage: "[arg2]",
			Action: func(cctx *cli.Context) error {
				return nil
			},
		},
	}
	err := app.Run(os.Args)
	if err != nil {
		panic(err)
	}
}
```

`go run test.go -h` will print:

```
NAME:
   test - A new cli application

USAGE:
   test [global options] command [command options] [arg1]

COMMANDS:
   cmd1
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h  show help
```

but `go run test.go cmd1 -h` will print:

```
NAME:
   test cmd1

USAGE:
   test cmd1 [command options][arg2]

OPTIONS:
   --help, -h  show help
```

## difference

there is no space between comand options and custom args usage.

```
   test [global options] command [command options] [arg1]

vs

   test cmd1 [command options][arg2]
```

**Review by Juneezee — COMMENTED** [review]
The `SubcommandHelpTemplate` seems to have the same whitespace problem too. Would you mind taking a look as well?

https://github.com/urfave/cli/blob/84c536d83870ebde3452049930a236e4724cb440/template.go#L82-L86

**Comment by caeret** [comment]
> The `SubcommandHelpTemplate` seems to have the same whitespace problem too. Would you mind taking a look as well?
> 
> https://github.com/urfave/cli/blob/84c536d83870ebde3452049930a236e4724cb440/template.go#L82-L86

I'm sorry that when modifying the code today, I missed some variables related to ArgsUsage for the sake of convenience in using the vim editor. The whitespace issue in the SubcommandHelpTemplate variable has now been fixed, and running 'go test ./...' shows no problems.

**Review by bartekpacia — APPROVED** [review]

**Comment by dearchap** [comment]
@caeret Sorry looks like I messed up the commit by force pushing v2-maint to your repo. . Can you repush your PR ? Also run "make docs" and "make v2approve"

**Comment by dearchap** [comment]
Closed by mistake

**Pull request closed without merging**
