### PR TITLE
Added manual and script for PowerShell autocomplete

### PR DESCRIPTION
**Pull request by kirinnee**
## What type of PR is this?
- [ ] bug
- [ ] cleanup  
- [x] documentation
- [x] feature

## What this PR does / why we need it:
This adds documentation and script to enable autocomplete on both
PowerShell and PS Core on Windows (and other platforms)

## Special notes for your reviewer:
Not sure how to automate testing

## Testing
Following instructions added to the manual in a PowerShell environment

### CODE REVIEW

**Comment by kirinnee** [comment]
Any updates? Or anything I need to improve before it can be merged?

**Comment by lynncyrin** [comment]
Oh, @kirinnee the docs tests are failing b/c you're missing a heading. Check the logs here => https://github.com/urfave/cli/pull/1139/checks?check_run_id=683967954

**Comment by kirinnee** [comment]
Hi I have updated accordingly. Please lmk if there are more changes needed! Thank you!

**Comment by kirinnee** [comment]
Any updates?

**Review by asahasrabuddhe — APPROVED** [review]
LGTM

**Pull request merged**
