### PR TITLE
StringSlice flags set to default Value

### PR DESCRIPTION
**Pull request by darren-west**
StringSliceFlag types do not set the destination to the value if no env/arg is set.

For example if the argument `--arg` is not set and env variable `ARG` is not set you would expect the destination to be set to `cli.NewStringSlice("foo")`
```go
                 var arg = cli.NewStringSlice()
		...
                  &cli.StringSliceFlag{
			Name:        "arg",
			EnvVars:     []string{"ARG"},
			Value:       cli.NewStringSlice("foo"),
			Destination: arg,
		},
```

I have quickly looked at how the string flag achieves this and tried to do similar.

### CODE REVIEW

**Comment by darren-west** [comment]
I have added a test. The idea is that if the destination is set and the value is set but the flag is not set by env name or a program argument the value sets the destination. This is more consistent with how the other flags work (for instance StringFlag)

**Comment by erikwilson** [comment]
It looks like this is a duplicate of #1127?

**Comment by lynncyrin** [comment]
It does look like this is a duplicate!

**Comment by meatballhat** [comment]
Confirmed already fixed via #1127

Thank you all the same @darren-west!

**Pull request closed without merging**
