### PR TITLE
Display `(accepts multiple inputs)` in the help description for Slice flags.

### LINKED ISSUE #1066: v2 feature: print text to indicate when a flag allow multiple values
## Checklist

* [x] Are you running the latest v2 release? 
* [x] Did you check the manual for your release?
* [x] Did you perform a search about this feature?

## What problem does this solve?

- need to print a text to know when a flag is a slice (allow multiple values)

## Solution description

I would want that after of the usage message were printed a text like i.e. `(multiple)`

### PR DESCRIPTION
**Pull request by Madhur1997**
## What type of PR is this?

- [x] bug

## What this PR does / why we need it:

For Slice flags, display an additional string `(accepts multiple inputs)` in the help description. This PR adds a support for it
and updates existing tests for accommodating this change.

## Which issue(s) this PR fixes:

Fixes #1066

## Testing

Updated Existing tests to accommodate the changes.
## Release Notes

```release-note
Display `(accepts multiple inputs)` in the help description for Slice flags.

```

### CODE REVIEW

**Comment by Madhur1997** [comment]
bumping this

**Comment by Madhur1997** [comment]
Failing check is unrelated.

**Review by lynncyrin — APPROVED** [review]
SGTM 👍🏼

**Comment by lynncyrin** [comment]
@Madhur1997 Can you pull in the default branch to fix the failing test please 🙏🏼

**Comment by Madhur1997** [comment]
sure, updated the PR. Thanks for the review.

**Review by lynncyrin — APPROVED** [review]

**Review by rliebz — APPROVED** [review]

**Pull request merged**
