### PR TITLE
Fix docs import

### PR DESCRIPTION
**Pull request by mouuff**

### CODE REVIEW

**Comment by mouuff** [comment]
https://github.com/urfave/cli/issues/917

**Comment by saschagrunert** [comment]
Hey @mouuff :wave:, the import should work if you're on a recent go version and using go modules. In which case did you see an error?

**Comment by mouuff** [comment]
Its building well on my computer but I get an error when building for docker
```
vendor/github.com/urfave/cli/docs.go:11:2: cannot find package "github.com/cpuguy83/go-md2man/v2/md2man" in any of:
	/go/src/gitlab.com/acklio/registry/vendor/github.com/cpuguy83/go-md2man/v2/md2man (vendor tree)
	/usr/local/go/src/github.com/cpuguy83/go-md2man/v2/md2man (from $GOROOT)
	/go/src/github.com/cpuguy83/go-md2man/v2/md2man (from $GOPATH)
```
Any ideas what could fix it?

**Comment by saschagrunert** [comment]
Hm, can you provide us the way how you build the container image to reproduce it on our side?

**Comment by asahasrabuddhe** [comment]
I am sorry @mouuff but I cannot merge this. The package name is correct as defined in the `go.mod` file of the original package. You can check it out here:

https://github.com/cpuguy83/go-md2man/blob/eda4fa589184806b8720ea3b9146491209877a10/go.mod#L1-L9

Also, we support only Go Modules and not any other dependency management system. It is officially supported by Go and not very difficult to migrate to.

**Pull request closed without merging**
