### PR TITLE
Add Frogbot workflows to this repository

### PR DESCRIPTION
**Pull request by eyalbe4**
## What type of PR is this?

- feature

## What this PR does / why we need it:

I'm opeening this PR following the discussion here - https://github.com/urfave/cli/discussions/1716 - about adding [Frogbot](https://github.com/jfrog/frogbot#readme) to this repository.

This PR includes two GitHub workflow files.
`frogbot-scan-and-fix.yml` - to allow scanning PRs.
`frogbot-scan-pr.yml` - to scan the repository following new commits.

## Special notes for your reviewer:

This PR should be merged after the steps discussed in https://github.com/urfave/cli/discussions/1716 are implemeneted.

## Testing

After the merge, we can test this by opening a test pull request and allow Frogbot to scan it. Then, following a merge of a pull request, we can look at the logs of workflow run added by `frogbot-scan-pr.yml`, to see it includes no errors.

## Release Notes

```release-note
Frogbot added to this repository
```

### CODE REVIEW

**Comment by dearchap** [comment]
@eyalbe4 I tried the instructions you provided but couldnt make progress . Can we get on a zoom call sometime ?

**Comment by eyalbe4** [comment]
Sure thing @dearchap.
Would you like to send me an email to eyalb@jfrog.com so that we can schedule our meeting?

**Comment by dearchap** [comment]
@eyalbe4 I sent you an email from my gmail account last month and havent heard back from you.

**Comment by eyalbe4** [comment]
Apologies @dearchap,
I see your email now. Let me reply there.

**Comment by dearchap** [comment]
@eyalbe4 I'm opened a separate PR #1778 with tested workflow files. Closing this for now

**Pull request closed without merging**
