### PR TITLE
show only subcommand flags with bash completion

### LINKED ISSUE #1184: How to get autocomplete to not show global flags for subcommand?
## my urfave/cli version is

_**v2.2.0**_

## Checklist

* [x] Are you running the latest v2 release? The list of releases is [here](https://github.com/urfave/cli/releases).
* [x] Did you check the manual for your release? The v2 manual is [here](https://github.com/urfave/cli/blob/master/docs/v2/manual.md)
* [x] Did you perform a search about this problem? Here's the [Github guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## Dependency Management

- [x] My project is using go modules.

## Describe the bug

I am using this wonderful library for [croc](https://github.com/schollz/croc). This utility has global flags and also flags for subcommands. Autocompletion works great, except that if I use a subcommand and autocomplete a flag, it shows the global flags and the flags for the subcommand, even though *only the subcommand flags can be used*.

## To reproduce

Describe the steps or code required to reproduce the behavior:

```
> git clone --depth 1 https://github.com/schollz/croc
> cd croc 
> go build
> ./croc send --<tab>
# shows subcommand flags + global flags that can't be used
```

## Observed behavior

Subcommand shows global flags:

```
> # shows global flags + subcommand
> ./croc send --<tab>
--ask          --no-compress  --pass         --remember     --yes        
--code         --no-local     --ports        --stdout                    
--debug        --no-multi     --relay        --text                      
--help         --out          --relay6       --version
```

Global flags (for reference):

```
> # global flags
> ./croc --<tab>
--ask          --no-compress  --relay        --stdout                    
--debug        --out          --relay6       --version                   
--help         --pass         --remember     --yes
```

## Expected behavior

I expected that autocompletion on subcommands only autocompletes flags that can be used on that subcommand. E.g. If you select a global flag from a subcommand flag autocompletion (e.g. `croc send --yes README.md`) it results in a `flag provided but not defined` error.

## Additional context

Repo: https://github.com/schollz/croc 

```
go version go1.15.1 linux/amd64
```

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/zns/.cache/go-build"
GOENV="/home/zns/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/zns/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/zns/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/croc/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build711943122=/tmp/go-build -gno-record-gcc-switches"
```

### PR DESCRIPTION
**Pull request by schollz**
## What type of PR is this?

- bug

## What this PR does / why we need it:

On subcommands the bash completion for flags shows *global* flags which cannot be used. This change makes sure that only subcommand flags are shown.

## Which issue(s) this PR fixes:

Fixes #1184

## Special notes for your reviewer:

None.

## Testing

I tested the change with my program, [croc](https://github.com/schollz/croc) to see if the subcommands (`croc send --`) correctly complete the flags for subcommands. 

## Release Notes

```release-note
bug fix: show only subcommand flags with bash completion
```

### CODE REVIEW

**Comment by schollz** [comment]
Is this blocked for some reason?

**Review by rliebz — APPROVED** [review]

**Comment by lynncyrin** [comment]
@schollz can you add a test case for this?

**Review by lynncyrin — CHANGES_REQUESTED** [review]
_(requesting changes for the test case)_

**Comment by schollz** [comment]
> @schollz can you add a test case for this?

Sorry, no I cannot. Feel free to close

**Pull request merged**
