### PR TITLE
Added script to generate altsrc flag definitions

### PR DESCRIPTION
**Pull request by ipostelnik**
Added script to generate altsrc flag definitions, restricted list of types to the ones that provide implementation of FlagInputSourceExtension.

## What type of PR is this?

- bug
- cleanup  

## What this PR does / why we need it:

- The original program to generate altsrc flags is nowhere to be found, so replaced with fg.py. 
- The types of altsrc flags are now limited to the subset that provide FlagInputSourceExtension implementation and have matching methods in InputSourceContext interface. Removed types where never updated from the input source.

## Testing

Existing unit tests

## Release Notes

Removed `altsrc` flag definitions for types that do not implement FlagInputSourceExtension. These types did not have their values loaded from the configuration file.

```release-note

```

### CODE REVIEW

**Comment by meatballhat** [comment]
@ipostelnik Sorry for the long delay! 😭 Any chance you're interested in refreshing this work, especially in light of [the most recent round of flag generation tooling](https://github.com/urfave/cli/pull/1382)?

**Review by dearchap — APPROVED** [review]

**Comment by meatballhat** [comment]
@dearchap if you're interested in seeing this work moved forward, I think I would prefer the use of the more recently-(re)introduced `internal/genflags`. WDYT?

**Comment by dearchap** [comment]
@meatballhat That should be fine. @ipostelnik Are you up to resolve the conflicts ?

**Comment by dearchap** [comment]
PR #1553 Does this on latest and uses the internal gen flag program.

**Pull request closed without merging**
