### PR TITLE
Remove Flag Generation

### PR DESCRIPTION
**Pull request by asahasrabuddhe**
Update Travis YAML to remove generation command

Add support for Go 1.13
Drop support for Go 1.11

### CODE REVIEW

**Comment by asahasrabuddhe** [comment]
Looks like there is something wrong with the master as it is failing almost everything.

**Comment by asahasrabuddhe** [comment]
Current Status:

All essential checks are passing except the diff after generating TOC since I have removed the parts of code in README.md referencing ShortOptionHandling as they are not available for use in v1.21.0

**Comment by lynncyrin** [comment]
> All essential checks are passing except the diff after generating TOC since I have removed the parts of code in README.md referencing ShortOptionHandling as they are not available for use in v1.21.0

Can you put this inside another PR? We'll want to revert it after release 1.22.0 https://github.com/urfave/cli/issues/867

**Comment by lynncyrin** [comment]
> Add support for Go 1.13
> Drop support for Go 1.11

I would also like for this go inside it's own PR 🙏 unless there's some specific reason it's included in this one?

**Pull request closed without merging**
