### PR TITLE
Bump Travis versions

### PR DESCRIPTION
**Pull request by HaraldNordgren**

### CODE REVIEW

**Comment by HaraldNordgren** [comment]
@AudriusButkevicius @jszwedko Ping

**Comment by AudriusButkevicius** [comment]
Why does this matter?

**Comment by HaraldNordgren** [comment]
@AudriusButkevicius It serves to prove that the project builds on newer Go versions and not just Go 1.8.

**Comment by AudriusButkevicius** [comment]
Go is backwards compatible. So I am not sure why do we need to prove this to anyone?

I don't mind the change, yet I don't see the material impact of this or the importance of this.

**Comment by AudriusButkevicius** [comment]
Done by a different pr

**Pull request closed without merging**
