### PR TITLE
app: Add App.Description

### PR DESCRIPTION
**Pull request by wking**
So you can describe what the application is for without requiring users to drill down into a particular command.

If this idea sounds usefull, I can add a test-case to this PR.

### CODE REVIEW

**Comment by jszwedko** [comment]
Hi @wking,

This was the intention of the `Usage` field -- do you have an example use case that might better show the distinction you are making here?

Thank you!

**Comment by wking** [comment]
On Tue, Oct 18, 2016 at 08:28:11PM -0700, Jesse Szwedko wrote:
> This was the intention of the `Usage` field -- do you have an
> example use case that might better show the distinction you are
> making here?

CommandHelpTemplate (vs. AppHelpTemplate) has separate USAGE and
DESCRIPTION sections.  I'm just proposing App allow the same
distinction.  And man(1) has [1]:

  Conventional section names include NAME, SYNOPSIS, CONFIGURATION,
  DESCRIPTION, OPTIONS, EXIT STATUS, RETURN VALUE, ERRORS,
  ENVIRONMENT, FILES, VERSIONS, CONFORMING TO, NOTES, BUGS, EXAMPLE,
  AUTHORS, and SEE ALSO.

Help generated by this package uses “USAGE” instead of “SYNOPSIS”, but
clearly distinguishing between invocation templates and plain text
discriptions is a fairly standard thing.

One benefit of the distinction is that you will be able to put plain
text in App.Description while still relying on the auto-generated
USAGE entries which would have been clobbered had you set
App.UsageText.

[1]: http://man7.org/linux/man-pages/man1/man.1.html#DESCRIPTION

**Comment by jszwedko** [comment]
@wking aha, I see! I missed that `Command` already allows for this. Do you mind adding a test for this? Otherwise I think it looks great.

**Comment by wking** [comment]
Test added (along with some whitespace fixups in `AppHelpTemplate` and `Author.String`) with c4a46a7 → 3c2bce5.

**Comment by jszwedko** [comment]
This looks great, thank you for adding the tests @wking

**Pull request merged**
