### PR TITLE
Use non-TLS gocov badges

### PR DESCRIPTION
**Pull request by meatballhat**

### CODE REVIEW

**Comment by jszwedko** [comment]
It looks like the issue is that gocover.io is serving an invalid certificate so we could also fix them by just using `http://` -- unless there was another reason you wanted to remove the image?

**Comment by meatballhat** [comment]
I originally switched to `http://` but that wasn't enough to appease the github camo caching servers 😐

**Comment by meatballhat** [comment]
I also tried some cache busting query params, but no luck there either.

**Comment by jszwedko** [comment]
Hrm, looking at https://github.com/github/markup/issues/224 it looks like it should respect cache headers returned by the request. In the current case (`https`) it should, and appears to, fail to fetch the resource.

I'd advocate for reverting to the `http` and, if it doesn't clear up in a day or two, reach out to their support.

**Comment by meatballhat** [comment]
le ugh 😛

**Comment by jszwedko** [comment]
:cry: 

Lemme reach out to their support.

**Comment by jszwedko** [comment]
Also opened an issue in gocover.io regarding the cert being served: https://github.com/vieux/gocover.io/issues/22

**Comment by meatballhat** [comment]
Whoops, no longer needed!

**Comment by jszwedko** [comment]
:tada:

**Pull request closed without merging**
