### PR TITLE
go.mod: Require go1.22

### LINKED ISSUE #2024: v3 error: flag_timestamp.go:92:44: undefined: time.TimeOnly
```
/go/pkg/mod/github.com/urfave/cli/v3@v3.0.0-beta1/flag_timestamp.go:92:44: undefined: time.TimeOnly
```
https://ci.codeberg.org/repos/13526/pipeline/30/6

### PR DESCRIPTION
**Pull request by mrueg**
## What type of PR is this?

- feature

## What this PR does / why we need it:

Require at least go 1.22
https://github.com/golang/go/issues/52746
## Which issue(s) this PR fixes:
Fixes #2024
## Release Notes

```release-note
Raise minimum go version to 1.22
```

### CODE REVIEW

**Review by Juneezee — APPROVED** [review]

**Review by yassinebenaid — COMMENTED** [review]
Wouldn't be better to just copy the layout from standard library.

I mean, if the reason for upgrading the version is to just use that time template _(time.TimeOnly)._ you can simply copy it (or write it manually). 

I'm not against upgrading to higher versions, it's just need to be for a good reason.

**Comment by mrueg** [comment]
Depends on what you want to support, given that this is a major version bump, the CI only checks for currently 1.22, 1.23 and 1.18 is EOL since almost 2 years (https://endoflife.date/go), I would recommend to probably even bump it to v1.22 (even if you don't need it that high).

**Comment by yassinebenaid** [comment]
Amm, Alright, In that case, considering the stability of the language. I agree with you that we can bump to`go 1.22` .

Thanks @mrueg. ❤️

**Review by dearchap — APPROVED** [review]

**Review by bartekpacia — APPROVED** [review]

**Comment by mrueg** [comment]
Do you want me to update the PR to go1.22?

**Comment by bartekpacia** [comment]
> Do you want me to update the PR to go1.22?

+1 from me :)

**Review by 6543 — APPROVED** [review]

**Comment by mrueg** [comment]
> > Do you want me to update the PR to go1.22?
> 
> +1 from me :)

Done :)

**Pull request merged**
