### PR TITLE
Ignore internal build dir

### PR DESCRIPTION
**Pull request by dearchap**
## What type of PR is this?

_(REQUIRED)_

- cleanup

## What this PR does / why we need it:

_(REQUIRED)_

Increase code coverage to beyond 90% for user facing code.

## Which issue(s) this PR fixes:

_(REQUIRED)_

## Special notes for your reviewer:

_(fill-in or delete this section)_

## Testing

_(fill-in or delete this section)_

## Release Notes

_(REQUIRED)_

```release-note

```

### CODE REVIEW

**Review by Juneezee — APPROVED** [review]
image

**Comment by abitrolly** [comment]
Looking at this `internal`/, maybe rename it into `scripts/`? Because `internal/` doesn't really tell what the dir is for.

**Comment by dearchap** [comment]
@abitrolly  you want to make the change in a separate PR ? I don't have bandwidth to do this now

**Comment by abitrolly** [comment]
@dearchap sure, here you go - https://github.com/urfave/cli/pull/1992

**Pull request merged**
