### PR TITLE
Add word-wrap support based on terminal size

### PR DESCRIPTION
**Pull request by saschagrunert**
Highly experimental and still WIP.

Refers to #287

### CODE REVIEW

**Comment by saschagrunert** [comment]
Hm, windows can be a problem here...

**Comment by asahasrabuddhe** [comment]
@saschagrunert You can refer to this [file](https://github.com/gosuri/uilive/blob/master/terminal_size_windows.go) for help with terminal size on Windows

**Comment by mostynb** [comment]
I opened #1119 with this change + a speculative fix for windows.

**Comment by saschagrunert** [comment]
> I opened #1119 with this change + a speculative fix for windows.

Ah thank you for taking this over, I'll close this one here.

**Pull request closed without merging**
