### PR TITLE
[v3]  merge altsrc with main package

### PR DESCRIPTION
**Pull request by lynncyrin**
## What type of PR is this?

_(REQUIRED)_

- [ ] bug
- [x] cleanup  
- [ ] documentation
- [ ] feature

## What this PR does / why we need it:

This is one of the first goals for the v3 release (via https://github.com/urfave/cli/issues/833#issue-476467837). This helps condense the public API by reducing two exposed packages from before into a single package.

## Release Notes

```release-note
- Remove `altsrc` package
- Add `FlagInputSourceExtension` interface to allow a value to be set on existing parsed flags through alternate sources like `JSON` or `TOML` etc.
```

### CODE REVIEW

**Comment by asahasrabuddhe** [comment]
Looks like I can take this off your hands :)

**Comment by lynncyrin** [comment]
@asahasrabuddhe yes please! I looked at it a bunch, but didn't commit anything 😆

**Comment by asahasrabuddhe** [comment]
We are back in business!

**Comment by asahasrabuddhe** [comment]
For some reason, github actions refuse to work on this PR. Will have to start a new one!

**Pull request closed without merging**
