### PR TITLE
Add HelpFlag as part of VisibleFlags.

### PR DESCRIPTION
**Pull request by harshavardhana**
Additionally also allow help command to be hidden

### CODE REVIEW

**Comment by harshavardhana** [comment]
Any feedback on this @jszwedko ?

**Comment by jszwedko** [comment]
Hi @harshavardhana,

Apologies for the delay in review. Do you mind adding some additional details about the what this change is enabling?

It also appears to alter the existing interface by changing the behavior of the `HideHelp` field. If that was intentional, we may need to retarget this to the `v2` branch to avoid breaking compatibility.

**Comment by wking** [comment]
Part of what this PR is doing is splitting `HideHelp` into separate booleans for the command and option.  That would let us address #222 and avoid things like listing:

```
USAGE:
    [global options] command [command options] [arguments...]
```

[for an app whose only command is `help`][1] where the meat of the app is in the app-level `Run`.  With this PR, setting `HideHelpCommand` but not `HideHelp` will give you:

```
USAGE:
    [global options] [arguments...]
```

I agree that there are backwards-compat concerns, but think we can address them with a slight tweak.  Instead of re-purposing `HideHelp`, I'd deprecate it (to be removed in v2) and add both `HideHelpCommand` and `HideHelpFlag`.  Then you could hide if the specific property was set or the deprecated generic property was set.  That covers all cases except:

1. Alice's new code sets `HideHelpFlag` `true`, and hands the `App` off to Bob's code.
2. Bob's old code sets `HideHelp` false, because it wants to ensure that the `--help` flag is visible.

Bob's usecase would work now (because the only way Alice could have disabled `--help` is via `HideHelp`), but Bob's usecase would break with my proposed approach.  Still, I think that passing `App` and `Command` instances around with different parties having different opinions on whether `--help` should be displayed is unlikely.  In most cases, these are only used locally within a single repository.

[1]: https://github.com/urfave/cli/blob/v1.20.0/app_test.go#L189-L193

**Comment by jszwedko** [comment]
@wking aha, I see, thank you for providing additional context. I like your idea of splitting out the flags and deprecating `HideHelp`.

**Comment by devmattrick** [comment]
Sorry for the ping, but are still plans to implement this?

**Comment by AkihiroSuda** [comment]
Any chance to get this reopened?

**Comment by lynncyrin** [comment]
@AkihiroSuda @devmattrick either of you are free to open a new PR! Please create an associated issue first though.

**Comment by AkihiroSuda** [comment]
Will try, https://github.com/urfave/cli/issues/523 seems the existing issue ticket that covers this.

**Comment by AkihiroSuda** [comment]
PR: https://github.com/urfave/cli/pull/1083

**Pull request closed without merging**
